# Jina Embeddings V4 Research Project Configuration

# 基础模型路径（包含预训练的Jina模型）
base_model_path: "/home/shebd/4_Collaboration/FYP2526/jina-embeddings-v4"

# 数据配置 
data:
  image_base_dir: "data/Images"

# 训练配置
training:
  output_dir: "outputs/models"
  batch_size: 3
  learning_rate: 1e-4
  epochs: 30
  use_lora: true
  
# wandb配置
wandb:
  entity: "smart-search-fyp"
  project: "jina-embeddings-finetune"
  enabled: true

# LoRA配置
lora:
  r: 16
  alpha: 16
  dropout: 0.1

# 系统配置
system:
  bf16: true
  max_seq_length: 256
