# User Configuration for shebd
# This file overrides system_config.yaml defaults for this user's environment

# Model path for shebd's environment
model:
  base_model_path: "/project/medimgfmod/Generalist/0_Pretrained/jina-embeddings-v4"

# Data paths for shebd's environment  
data:
  train_data: "/home/shebd/4_Collaboration/FYP2526/data/train_full_path.jsonl"
  eval_data: "/home/shebd/4_Collaboration/FYP2526/data/eval.jsonl"

# Training configuration for current experiments
training:
  output_dir: "/home/shebd/4_Collaboration/FYP2526/output/models/run_9.7_liam"

# Loss weights configuration (currently equal weights)
loss:
  w1_single: 1.0                          # Weight for single-vector InfoNCE loss
  w2_multi: 1.0                           # Weight for multi-vector InfoNCE loss  
  w3_kl: 1.0                              # Weight for KL divergence loss

# Evaluation paths for shebd's environment
evaluation:
  eval_data_jsonl: "/home/shebd/4_Collaboration/FYP2526/data/eval_full_path.jsonl"
  eval_model_path: "/home/shebd/4_Collaboration/FYP2526/output/models/run_9.7_fred/checkpoint-2500"
  eval_base_model_path: "/project/medimgfmod/Generalist/0_Pretrained/jina-embeddings-v4"
